### ISSUE TITLE
python-script action runner is not able to find the python_terraform module

### ISSUE THREAD

**Issue by Sheshagiri** [StackStorm-Exchange/stackstorm-terraform#18]
Following is the error while trying to run an action that is present in this pack.

```
jet@jet-managed-st2:/opt/stackstorm/virtualenvs$ st2 run terraform.init plan_path="some-random-path"
.
id: 5eba728d06322785621125cd
action.ref: terraform.init
context.user: st2admin
parameters:
  plan_path: some-random-path
status: failed
start_timestamp: Tue, 12 May 2020 09:55:25 UTC
end_timestamp: Tue, 12 May 2020 09:55:26 UTC
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 237, in _get_action_instance
    actions_cls = action_loader.register_plugin(Action, self._file_path)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/loader.py", line 167, in register_plugin
    module = imp.load_source(module_name, plugin_abs_file_path)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/stackstorm/packs/terraform/actions/init.py", line 2, in <module>
    from lib import action
  File "/opt/stackstorm/packs/terraform/actions/lib/action.py", line 2, in <module>
    from python_terraform import Terraform
ModuleNotFoundError: No module named 'python_terraform'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 333, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 191, in run
    action = self._get_action_instance()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 244, in _get_action_instance
    raise exc_cls(msg)
ModuleNotFoundError: Failed to load action class from file "/opt/stackstorm/packs/terraform/actions/init.py" (action file most likely doesn't exist or contains invalid syntax): No module named 'python_terraform'

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 237, in _get_action_instance
    actions_cls = action_loader.register_plugin(Action, self._file_path)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/loader.py", line 167, in register_plugin
    module = imp.load_source(module_name, plugin_abs_file_path)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/stackstorm/packs/terraform/actions/init.py", line 2, in <module>
    from lib import action
  File "/opt/stackstorm/packs/terraform/actions/lib/action.py", line 2, in <module>
    from python_terraform import Terraform
ModuleNotFoundError: No module named 'python_terraform'

"
  stdout: ''
````

**Comment by Sheshagiri** [comment]
I found that pinning the `python-terraform` to `0.10.1` solved the above-mentioned issue. However, I'm not sure why the module was not visible to the action runner in spite of the module being installed in the virtual env of the pack.

```
jet@jet-managed-st2:/opt/stackstorm/virtualenvs$ source terraform/bin/activate
(terraform) jet@jet-managed-st2:/opt/stackstorm/virtualenvs$ pip list
Package          Version Location
---------------- ------- ----------------------------------------------------------
pip              19.1.1
python-terraform 0.10.2  /opt/stackstorm/virtualenvs/terraform/src/python-terraform
setuptools       41.0.1
six              1.14.0
wheel            0.33.4
WARNING: You are using pip version 19.1.1, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(terraform) jet@jet-managed-st2:/opt/stackstorm/virtualenvs$ python
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from python_terraform import Terraform
>>>
>>> quit()
(terraform) jet@jet-managed-st2:/opt/stackstorm/virtualenvs$ deactivate
jet@jet-managed-st2:/opt/stackstorm/virtualenvs$
```
